swagger: '2.0'
info: {title: Graph - Teams, description: '', version: '1.0'}
host: graph.microsoft.com
basePath: /v1.0
schemes: [https]
consumes: []
produces: []
paths:
  /chats:
    post:
      responses:
        default:
          description: default
          schema: {}
      summary: Create one-on-one chat
      description: Create one-on-one chat
      operationId: Chat
      parameters:
      - name: body
        in: body
        required: true
        schema:
          type: object
          properties:
            chatType: {type: string, description: chatType, title: '', default: oneOnOne,
              x-ms-visibility: internal}
            members:
              type: array
              items:
                type: object
                properties:
                  '@odata.type': {type: string, description: '@odata.type', title: '',
                    default: '#microsoft.graph.aadUserConversationMember', x-ms-visibility: internal}
                  roles:
                    type: array
                    items: {type: string, default: owner}
                    description: roles
                    x-ms-visibility: internal
                  user@odata.bind: {type: string, description: 'Must be in the form
                      https://graph.microsoft.com/v1.0/users(''userGUID'')', title: User}
                required: [user@odata.bind, '@odata.type']
              description: members
          required: [chatType, members]
  /users/{id|userPrincipalName}:
    get:
      responses:
        default:
          description: default
          schema: {}
      summary: Get user
      description: Get user
      operationId: User
      parameters:
      - {name: id|userPrincipalName, in: path, required: true, type: string}
definitions: {}
parameters: {}
responses: {}
securityDefinitions:
  oauth2_auth:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://login.windows.net/common/oauth2/authorize
    tokenUrl: https://login.windows.net/common/oauth2/authorize
    scopes: {}
security:
- oauth2_auth: []
tags: []
